#robot settings
wall_penalty: -5
empty_catching: -1
reward: 10
mutation_rate: 0.01
total_moves: 200

north: '0'
south: '1'
east: '2'
west: '3'
random: '4'
no_movement: '5'
catch_rubbish: '6'

#population settings
population-size: 200

#world settings
rubbish_probability: 0.5
world_size: 10
wall: '2'
rubbish: '1'
empty_space: '0'